import Objetos.Empleado;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class InicioSesion extends javax.swing.JFrame {

    static DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel();
    static ArrayList<Empleado> empleados = new ArrayList<Empleado>();
    public static Empleado empleado;
    
    
    public InicioSesion() {
        initComponents();
        
        cargarEmpleados();
        ComboBox.setModel(modeloComboBox);
        cambiarImagen();
        cambiarNombre();
        cambiarCargo();
        txtPass.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBox = new javax.swing.JComboBox<>();
        btnInicio = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesión");
        setResizable(false);

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInicio.setText("INICIAR SESIÓN");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblCargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 163, Short.MAX_VALUE)
                    .addComponent(txtPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInicio)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Empleado e = (Empleado) modeloComboBox.getElementAt(ComboBox.getSelectedIndex());
        if(e.getPass().equals(txtPass.getText())){
            empleado=e;
            Registro.addRegistro("El empleado "+InicioSesion.empleado.getNombre()+" "+InicioSesion.empleado.getApellido()+" ha iniciado sesión");
            Menu m = new Menu();
            m.setVisible(true);
            super.setVisible(false);
        }
        else{
            System.out.println(e.getPass()+"    "+txtPass.getText());
            JOptionPane.showMessageDialog(null, "Combinaciónde usuario + contraseña incorrecto", "ERROR", JOptionPane.WARNING_MESSAGE);
            txtPass.setText("");
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        cambiarImagen();
        cambiarNombre();
        cambiarCargo();
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        if(evt.getKeyCode()==10){
            Empleado e = (Empleado) modeloComboBox.getElementAt(ComboBox.getSelectedIndex());
            if(e.getPass().equals(txtPass.getText())){
                empleado=e;
                Registro.addRegistro("El empleado "+InicioSesion.empleado.getNombre()+" "+InicioSesion.empleado.getApellido()+" ha iniciado sesión");
                Menu m = new Menu();
                m.setVisible(true);
                super.setVisible(false);
            }
            else{
                System.out.println(e.getPass()+"    "+txtPass.getText());
                JOptionPane.showMessageDialog(null, "Combinaciónde usuario + contraseña incorrecto", "ERROR", JOptionPane.WARNING_MESSAGE);
                txtPass.setText("");
            }
        }
    }//GEN-LAST:event_txtPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    static void cargarEmpleados(){
        modeloComboBox.removeAllElements();
        if(BD.conexion != null) {
            System.out.println("Conexion realizada con éxito");
        }
        //Paso 2: Ejecutar una consulta
        try{
            ResultSet rs = null;
            Statement sentencia = BD.conexion.createStatement();
            String sql = "SELECT * FROM empleado";
            rs = sentencia.executeQuery(sql);
            //Paso 3: Extrayendo los datos del resultset
            while(rs.next()) {
            //Recuperar datos por el nombre de la columna
            String codigo = rs.getString("cod_empleado");
            String nombre = rs.getString("nombre");
            String apellido = rs.getString("apellido");
            String pass = rs.getString("pass");
            String puesto= rs.getString("puesto");
            byte[] img = rs.getBytes("imagen");
            //Ver valores
            modeloComboBox.addElement(new Empleado( Integer.parseInt(codigo) , nombre , apellido , pass, puesto, img));
                }
        }
        catch (SQLException ex) {
            System.out.println("Error"+ex);
                }
    }
    static void cambiarImagen(){
        if(ComboBox.getSelectedIndex()==-1){
            return;
        }
        Empleado e = (Empleado) modeloComboBox.getElementAt(ComboBox.getSelectedIndex());
        ImageIcon icon = new ImageIcon(e.getImg());
        Icon fondo = new ImageIcon(icon.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_DEFAULT));
        lblImg.setIcon(fondo);
        lblImg.repaint(); 
    }
    static void cambiarNombre(){
        if(ComboBox.getSelectedIndex()==-1){
            return;
        }
        Empleado e = (Empleado) modeloComboBox.getElementAt(ComboBox.getSelectedIndex());
        lblNombre.setText(e.getNombre()+" "+e.getApellido());
    }
    static void cambiarCargo(){
        if(ComboBox.getSelectedIndex()==-1){
            return;
        }
        Empleado e = (Empleado) modeloComboBox.getElementAt(ComboBox.getSelectedIndex());
        lblCargo.setText(e.getPuesto());
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel lblCargo;
    private static javax.swing.JLabel lblImg;
    private static javax.swing.JLabel lblNombre;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
